name: Matchbox
vendor: SCAPE	
maintainer:
	name: Alexander Schindler
	email: alexander( DOT )schindler( AT )ait.ac.uk
	name: Reinhold Huber-Mork
	email: Reinhold( DOT )Huber-Moerk( AT )ait( DOT )ac( DOT )at
