language: cpp
compiler:
  - gcc
before_install:
# not using OpenCV 2.4.7.exe as it does not include mingw libs
  - OPENCVEXE=OpenCV-2.4.6.0.exe
  - wget -O $OPENCVEXE.7z http://sourceforge.net/projects/opencvlibrary/files/opencv-win/2.4.6/$OPENCVEXE/download
  - wget ftp://mirrors.kernel.org/sourceware/cygwin/x86/release/boost/libboost1.53/libboost1.53-1.53.0-2.tar.bz2
  - wget ftp://mirrors.kernel.org/sourceware/cygwin/x86/release/boost/libboost-devel/libboost-devel-1.53.0-2.tar.bz2
# will probably need other libraries
  - sudo apt-get install p7zip
install:
  - p7zip -d $OPENCVEXE.7z
  - sudo cp -rf opencv/build/include/ /usr/i586-mingw32msvc/
  - sudo cp -rf opencv/build/x86/mingw/* /usr/i586-mingw32msvc/
  # fix permissions
  - sudo chmod a+rx -R /usr/i586-mingw32msvc/include/opencv
  - sudo chmod a+rx -R /usr/i586-mingw32msvc/include/opencv2
  - sudo apt-get update
  - sudo apt-get install mingw32
  - pushd .
  - TBZ2DIR=`pwd`
  - cd /usr/i586-mingw32msvc/
  - sudo tar jxf $TBZ2DIR/libboost1.53-*.tar.bz2
  - sudo tar jxf $TBZ2DIR/libboost-devel-*.tar.bz2
  - popd
before_script:
# This is the path to the installed OpenCVConfig.cmake
# NOTE: a *full* path to the file should be passed to cmake, hence the addition of `pwd`
  - mkdir build && cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=../mingw32-cross-compile.cmake -DOpenCV_DIR=/usr/i586-mingw32msvc/lib/
script: 
  - make
  - cpack -G TGZ
after_success:
  - echo 