language: cpp
compiler:
  - gcc
install:
  - wget -O opencv-2.4.6.1.tar.gz http://downloads.sourceforge.net/project/opencvlibrary/opencv-unix/2.4.6.1/opencv-2.4.6.1.tar.gz && tar zxf opencv-2.4.6.1.tar.gz
  - cd opencv-2.4.6.1
  - mkdir build
  - cd build
  - mkdir ../../opencv
  - cmake .. -DCMAKE_INSTALL_PREFIX=../../opencv
  - make
  - make install
  - cd ../..
before_script:
  - mkdir build
  - cd build
  - cmake .. -DOpenCV_DIR=../opencv
script: 
  - make